# Generated by Django 3.1.7 on 2021-04-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='practitionerrole',
            name='role_name',
        ),
        migrations.AddField(
            model_name='practitionerrole',
            name='role_name',
            field=models.ManyToManyField(null=True, to='Application.Role'),
        ),
    ]
