# Generated by Django 3.1.7 on 2021-04-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_auto_20210406_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practitionerrole',
            name='organization',
        ),
        migrations.AddField(
            model_name='practitionerrole',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.organization'),
        ),
        migrations.RemoveField(
            model_name='practitionerrole',
            name='role_name',
        ),
        migrations.AddField(
            model_name='practitionerrole',
            name='role_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.role'),
        ),
    ]
